name = "Hypixel Skyblock Modpack"
author = "Soul-Returns"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e71e8b1eeef86b72d8757afe89a3d2237f86c30767ae4919a36f2915b5b8cee5"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
