name = "Hypixel Skyblock Modpack"
author = "Soul-Returns"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "188217fa07d510e618c309386879ecc6b7aa6d93bb1eeff7910cf1bbafdc3bc3"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
